# Generated by Django 2.0.5 on 2019-05-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('year_from', models.DateField()),
                ('year_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('exp_years', models.IntegerField()),
                ('college_degree', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('about_me', models.TextField()),
            ],
        ),
    ]
